
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yonatanembiza/e-commerce-configurations.git
          clone-on-start: true
server:
  port: 3000

logging:
  level:
    org.springframework.cloud.config: DEBUG